### ISSUE TITLE
bug-7 crashes when second user logs on

### ISSUE THREAD

**Issue by nathalie-tate** [OakAces/acechat-server#13]
INFO:acechat.server:Server starting
INFO:acechat.server:<- {"command":"USER","args":["Anthony"]}
INFO:acechat.server:-> {"command": "USER", "args": ["Anthony"], "user": "Anthony", "timestamp": 1477958289.5912607}
INFO:acechat.server:<- {"command":"JOIN","args":["Default Channel"]}
INFO:acechat.server:-> {"command": "JOIN", "args": ["Default Channel", "Anthony"], "user": "Anthony", "timestamp": 1477958289.5917027}
INFO:acechat.server:<- {"command":"CHANLIST","args":[]}
INFO:acechat.server:-> {"command": "CHANLIST", "args": ["Default Channel"], "user": "Anthony", "timestamp": 1477958289.5920503}
INFO:acechat.server:<- {"command":"USERLIST","args":[]}
INFO:acechat.server:-> {"command": "USERLIST", "args": ["Anthony"], "user": "Anthony", "timestamp": 1477958289.5923903}
INFO:acechat.server:<- {"command":"CHANLIST","args":[]}
INFO:acechat.server:-> {"command": "CHANLIST", "args": ["Default Channel"], "user": "Anthony", "timestamp": 1477958289.5927258}
INFO:acechat.server:<- {"command":"USER","args":["Ryan"]}
INFO:acechat.server:-> {"command": "USER", "args": ["Ryan"], "user": "Ryan", "timestamp": 1477958295.6772497}
INFO:acechat.server:<- {"command":"JOIN","args":["Default Channel"]}
Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 236, in cmd_join
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 312, in send_obj
    data = json.dumps(obj)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <acechat.user.User object at 0xb68b36cc> is not JSON serializable
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 236, in cmd_join
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 312, in send_obj
    data = json.dumps(obj)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <acechat.user.User object at 0xb68b36cc> is not JSON serializable
INFO:websockets.protocol:Failing the WebSocket connection: 1011 
INFO:websockets.protocol:Failing the WebSocket connection: 1006 
INFO:acechat.server:<- {"command":"USERLIST","args":[]}
INFO:acechat.server:-> {"command": "USERLIST", "args": ["Anthony", "Ryan"], "user": "Anthony", "timestamp": 1477958320.7580867}
INFO:acechat.server:<- {"command":"CHANLIST","args":[]}
INFO:acechat.server:-> {"command": "CHANLIST", "args": ["Default Channel"], "user": "Anthony", "timestamp": 1477958320.7634542}
INFO:acechat.server:<- {"command":"MSG","args":["Default Channel","hello"]}
INFO:acechat.server:-> {"command": "MSG", "args": ["Default Channel", "hello"], "user": "Anthony", "timestamp": 1477958320.7639568}
INFO:acechat.server:-> {"command": "MSG", "args": ["Default Channel", "hello"], "user": "Anthony", "timestamp": 1477958320.7643995}
Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 184, in cmd_msg
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 314, in send_obj
    await conn.send(data)
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 309, in send
    yield from self.ensure_open()
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 393, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1011, no reason.
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 184, in cmd_msg
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 314, in send_obj
    await conn.send(data)
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 309, in send
    yield from self.ensure_open()
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 393, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1011, no reason.
INFO:websockets.protocol:Failing the WebSocket connection: 1011 
INFO:websockets.protocol:Failing the WebSocket connection: 1006

**Comment by nathalie-tate** [comment]
INFO:acechat.server:Server starting
INFO:acechat.server:<- {"command":"USER","args":["Test0"]}
INFO:acechat.server:-> {"user": "Test0", "command": "USER", "timestamp": 1477958633.974412, "args": ["Test0"]}
INFO:acechat.server:<- {"command":"JOIN","args":["Default Channel"]}
INFO:acechat.server:-> {"user": "Test0", "command": "JOIN", "timestamp": 1477958633.976181, "args": ["Default Channel", "Test0"]}
INFO:acechat.server:<- {"command":"CHANLIST","args":[]}
INFO:acechat.server:-> {"user": "Test0", "command": "CHANLIST", "timestamp": 1477958633.9766192, "args": ["Default Channel"]}
INFO:acechat.server:<- {"command":"USERLIST","args":[]}
INFO:acechat.server:-> {"user": "Test0", "command": "USERLIST", "timestamp": 1477958633.9769955, "args": ["Test0"]}
INFO:acechat.server:<- {"command":"CHANLIST","args":[]}
INFO:acechat.server:-> {"user": "Test0", "command": "CHANLIST", "timestamp": 1477958633.9773586, "args": ["Default Channel"]}
INFO:acechat.server:<- {"command":"USER","args":["Test1"]}
INFO:acechat.server:-> {"user": "Test1", "command": "USER", "timestamp": 1477958646.422044, "args": ["Test1"]}
INFO:acechat.server:<- {"command":"JOIN","args":["Default Channel"]}
Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 236, in cmd_join
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 312, in send_obj
    data = json.dumps(obj)
  File "/usr/lib/python3.5/json/**init**.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <acechat.user.User object at 0xb6872e0c> is not JSON serializable
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 33, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 236, in cmd_join
    await self.send_obj(member, r)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 312, in send_obj
    data = json.dumps(obj)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <acechat.user.User object at 0xb6872e0c> is not JSON serializable
INFO:websockets.protocol:Failing the WebSocket connection: 1011 
INFO:websockets.protocol:Failing the WebSocket connection: 1006
