### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by nathalie-tate** [OakAces/acechat-server#19]
Just started implementing invite client side, seems to be broken server side 
```
<- nathalie {"command":"INVITE","args":["new","dan"]}
Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 35, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 308, in cmd_invite
    await self.send_obj(r)
TypeError: send_obj() missing 1 required positional argument: 'obj'
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/websockets/server.py", line 81, in handler
    yield from self.ws_handler(self, path)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 35, in handler
    await self.process_cmd(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 100, in process_cmd
    await f(user, obj)
  File "/home/nathalie/src/cse280Aces/acechat-server/acechat/server.py", line 308, in cmd_invite
    await self.send_obj(r)
TypeError: send_obj() missing 1 required positional argument: 'obj'
INFO:websockets.protocol:Failing the WebSocket connection: 1011 
INFO:websockets.protocol:Failing the WebSocket connection: 1006 
```

**Comment by dyladan** [comment]
Not implemented yet. I'll work on this tonight
